services:
  book-store-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - TZ=Asia/Bangkok
    ports:
      - "5432:5432"
    volumes:
      - postgres-book-store-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-book-store-data:
